apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: node-local-dns
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      chart: node-local-dns
      version: ''
      sourceRef:
        kind: HelmRepository
        name: node-local-dns
        namespace: flux-system
  values:
    # Inline environment-specific values can be provided here
