# clusters/flux-demo-dev/external-dns.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: nginx-ingress
namespace: kube-system
resources:
  - ../../../../common/helm-release/nginx-ingress

configMapGenerator:
  - name: nginx-ingress-values
    namespace: kube-system
    files:
      - values.yaml
    options:
      disableNameSuffixHash: true

patches:
  - target:
      kind: HelmRelease
      name: nginx-ingress
    path: patches.yaml
