controller:
  kind: deployment
  replicaCount: 1
  watchIngressWithoutClass: true
  service:
    type: NodePort
    httpPort:
      nodePort: 30080
      servicePort: 80
    httpsPort:
      nodePort: 30443
      servicePort: 443
