apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: helm-charts-dev
  namespace: flux-system
spec:
  interval: 5m
  path: ./clusters/flux-demo-dev/helm-release
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-demo
    namespace: flux-system
  # Default namespace for Helm releases when no namespace is specified
  # in the HelmRelease spec.
  targetNamespace: kube-system
  # Depend on the shared Helm charts Kustomization to ensure
  # that the HelmRelease resources are applied in the correct order.
  dependsOn:
    - name: shared-helm-charts
