apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-demo-dev
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./clusters/flux-demo-dev
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
