apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - helm-releases
# commonLabels:
#   team: k8s-techops
#   environment: flux-dev
#   managed-by: flux
#   region: local
#   cluster: kind-flux-dev
#   project: flux-demo
