# clusters/flux-demo-dev/external-dns.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: external-dns
namespace: kube-system
resources:
  - ../../../common/helm-releases/external-dns.yaml

configMapGenerator:
  - name: external-dns-values
    files:
      - values.yaml

patches:
  - target:
      kind: HelmRelease
      name: external-dns
    path: patches.yaml
