# clusters/flux-demo-dev/external-dns.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - github.com/k-weaver/flux-shared//helm-release/external-dns?ref=main

configMapGenerator:
  - name: external-dns-override-values
    namespace: kube-system
    files:
      - override.values.yaml
    options:
      disableNameSuffixHash: true

patches:
  - path: patch-values.yaml
