# clusters/flux-demo-dev/external-dns.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: external-dns
resources:
  - github.com/k-weaver/flux-shared//helm-release/external-dns?ref=main

patches:
  - path: patch-values.yaml
configMapGenerator:
  - name: external-dns-value-overrides
    namespace: kube-system
    files:
      - override.values.yaml
    options:
      disableNameSuffixHash: true
