# clusters/flux-demo-dev/external-dns.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: external-dns
namespace: kube-system
resources:
  - ../../../../common/helm-release/external-dns

configMapGenerator:
  - name: external-dns-values
    namespace: kube-system
    files:
      - values.yaml
    options:
      disableNameSuffixHash: true

patches:
  - target:
      kind: HelmRelease
      name: external-dns
    path: patches.yaml
