apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns
  namespace: kube-system
spec:
  chart:
    spec:
      version: 1.16.1
  valuesFrom:
    - kind: ConfigMap
      name: external-dns-override-values
      valuesKey: override.values.yaml
