apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns
spec:
  chart:
    spec:
      version: 1.16.2
  # valuesFrom:
  #   - configMapKeyRef:
  #       name: external-dns-dev-overrides
  #       key: values.yaml
