service:
  type: NodePort
  nodePort: 30001
  externalPort: 80
  httpPort: 9898

ingress:
  enabled: true
  className: 'nginx'
  hosts:
    - host: podinfo.local
      paths:
        - path: /
          pathType: Prefix
