service:
  type: LoadBalancer
  nodePort: 30001
  externalPort: 80
  httpPort: 9898

ingress:
  enabled: true
  className: 'nginx'
  additionalLabels: {}
  hosts:
    - host: podinfo.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: podinfo
                port:
                  number: 80
