securityContext:
  privileged: false
  runAsUser: 1001
  runAsGroup: 1001
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: false
  capabilities:
    drop:
      - ALL
    add:
      - NET_ADMIN
      - NET_RAW

podSecurityContext:
  fsGroup: 1001
  runAsGroup: 1001
  runAsUser: 1001
