apiVersion: v1
data:
  values.yaml: |
    namespace: 'kube-system'

    serviceAccount:
      create: true
      name: 'external-dns-sa'
kind: ConfigMap
metadata:
  name: external-dns-value-overrides
  namespace: kube-system
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns
  namespace: kube-system
spec:
  chart:
    spec:
      chart: external-dns
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: flux-system
      version: 1.16.2
  dependsOn:
  - name: external-dns
    namespace: flux-system
  interval: 5m
  valuesFrom:
  - configMapKeyRef:
      key: values.yaml
      name: external-dns-dev-overrides
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: external-dns
  namespace: kube-system
spec:
  interval: 60m
  url: https://kubernetes-sigs.github.io/external-dns
