apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: keda
  namespace: techops
spec:
  dependsOn:
    - kind: ConfigMap
      name: replaced-by-patch
  interval: 5m
  chart:
    spec:
      chart: keda
      version: 2.16.1
      sourceRef:
        kind: HelmRepository
        name: keda
        namespace: flux-system
  values:
    # Inline environment-specific values can be provided here
  valuesFrom:
    - configMapKeyRef:
        name: keda-values
        key: values.yaml
