# clusters/flux-demo-dev/keda.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: kyverno

resources:
  - ../../../../common/helm-release/kyverno

configMapGenerator:
  - name: kyverno-values
    namespace: kyverno
    files:
      - values.yaml
    options:
      disableNameSuffixHash: true

patches:
  - target:
      kind: HelmRelease
      name: kyverno
    path: patches.yaml
