apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-dns-configmaps
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./clusters/flux-demo-dev/helm-releases/external-dns/configmaps
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: kube-system
  wait: true
