apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: flux-shared
  labels:
    app: flux-shared
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/k-weaver/flux-shared
  ref:
    branch: main
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: flux-demo
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/k-weaver/flux-demo
  ref:
    branch: main
