apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: Namespace
    metadata:
      name: techops
  - apiVersion: v1
    kind: Namespace
    metadata:
      name: metrics
  - apiVersion: v1
    kind: Namespace
    metadata:
      name: sample-app
