prometheus:
  url: http://prometheus-server.kube-system.svc.cluster.local
  port: 80
logLevel: 6
rules:
  default: false
  external: []
  custom:
    - seriesQuery: '{__name__="nginx_ingress_nginx_connections_active"}'
      resources:
        overrides:
          namespace:
            resource: namespace
      name:
        matches: 'nginx_ingress_nginx_connections_active'
        as: 'nginx_ingress_connections'
      metricsQuery: 'sum(nginx_ingress_nginx_connections_active) by (namespace)'
