kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
  - role: worker
  - role: worker
  - role: worker
    # kubeadmConfigPatches:
    #   - |
    #     kind: KubeletConfiguration
    #     apiVersion: kubelet.config.k8s.io/v1beta1
    #     nodeRegistration:
    #       kubeletExtraArgs:
    #         register-with-taints: "dedicated=<taint>:NO_EXECUTE"
